name: Run JIRA US Fetcher

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'  # Exécute tous les jours à 8h UTC (à adapter)

jobs:
  fetch-jira-us:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # ou la version que tu souhaites

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run JIRA User Stories script
      env:
        JIRA_DOMAIN: ${{ secrets.JIRA_DOMAIN }}
        EMAIL: ${{ secrets.JIRA_EMAIL }}
        API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
      run: |
        python export.py
        
